KerasJson: stroke_read_model.json
KerasH5: stroke_lstm_model.weights.h5
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7a35tcpg236-1
ClockPeriod: 10ns

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency # options: Latency/Resource
