Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    batch_normalization_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    conv1d_6:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_6_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1d_7:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_7_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1d_8:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_8_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_4:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_4_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_5:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_5_softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
    input_layer_2:
      Precision:
        result: fixed<16,6>
      Trace: false
    lstm_4:
      Direction: forward
      Precision:
        bias: fixed<16,6>
        recurrent_bias: fixed<16,6>
        recurrent_weight: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    lstm_5:
      Direction: forward
      Precision:
        bias: fixed<16,6>
        recurrent_bias: fixed<16,6>
        recurrent_weight: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'my-hls-test/keras_model.h5'
OutputDir: my-hls-test
OutputPredictions: null
Part: xc7a35tcpg236-1
ProjectName: myproject
Stamp: b3D3aE64
Version: 1.0.0
