Backend: Vivado
ClockPeriod: 5
HLSConfig:
  LayerName:
    batch_normalization_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        scale: fixed<16,6>
      Trace: false
    conv1d_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_3_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1d_4:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_4_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    conv1d_5:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    conv1d_5_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_2_linear:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_3_softmax:
      Precision:
        result: fixed<16,6>
      Trace: false
    input_layer_1:
      Precision:
        result: fixed<16,6>
      Trace: false
    lstm_2:
      Direction: forward
      Precision:
        bias: fixed<16,6>
        recurrent_bias: fixed<16,6>
        recurrent_weight: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    lstm_3:
      Direction: forward
      Precision:
        bias: fixed<16,6>
        recurrent_bias: fixed<16,6>
        recurrent_weight: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'my-hls-test/keras_model.h5'
OutputDir: my-hls-test
OutputPredictions: null
Part: xc7a35tcpg236-1
ProjectName: myproject
Stamp: 04c6Dd58
Version: 1.0.0
